---
- name: Configure RHEL LINUX SERVER
  hosts: localhost # ansible-playbook setup.yml --ask-become-pass
  become: yes
  tasks:
  - name: Ensure the system is updated
    yum:
      name: "*"
      state: latest

  - name: Install EPEL repository
    yum:
      name: epel-release
      state: present

  - name: Install required packages
    yum:
      name:
      - ansible
      - aria2
      - curl
      - git
      - tuned
      - neovim
      - tmux
      - dnf-automatic
      - kpatch
      - cockpit
      - cockpit-pcp
      - cockpit-storaged
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-ostree
      - cockpit-machines
      - cockpit-podman
      - cockpit-selinux
      - cockpit-kdump
      - cockpit-sosreport
      - cockpit-files
      - cockpit-composer
      - virt-manager
      - qemu-kvm
      - libvirt
      - virt-install
      - bridge-utils
      state: present

  - name: Enable and start Cockpit service
    systemd:
      name: cockpit
      state: started
      enabled: yes

  - name: Enable and start libvirtd service
    systemd:
      name: libvirtd
      state: started
      enabled: yes

  - name: Disable lid switch handling (logind.conf configuration)
    lineinfile:
      path: /etc/systemd/logind.conf
      regexp: "^#?HandleLidSwitch.*"
      line: "HandleLidSwitch=ignore"
      state: present



### TMUX Plugin manager
### https://github.com/tmux-plugins/tpm?tab=readme-ov-file
###